spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/hotel_workforce?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop   # auto-creates tables from entities on start, drops on stop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false            # use ddl-auto in dev instead

logging:
  level:
    com.example.SWP391_G2_SE2055_JV: DEBUG
    org.hibernate.SQL: DEBUG
